# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'core-blogger-site-dev'

steps:
- script: dotnet test ./tests/CoreBlogger.Tests/
  displayName: 'Running Unit Tests'
- script:  docker login -u $(dockerId) -p $(pswd)
  displayName: 'Docker Hub Login'
- script: docker build -f ./src/Dockerfile -t $(dockerId)/$(imageName) ./src/
  displayName: 'Docker Build'
- script:  docker push $(dockerId)/$(imageName)
  displayName: 'Docker Push'
    
