# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'core-blogger-site'

steps:
- script:  docker login -u $(dockerId) -p $(pswd)
- script: docker build -f ./src/Dockerfile -t $(dockerId)/$(imageName) ./src/
- script:  docker push $(dockerId)/$(imageName)
  displayName: 'docker build'
    